language: ruby
rvm:
  - 2.3.1
before_script:
  - bundle exec rspec
addons:
  code_climate: 
  repo_token: b7b0b7b2e9cfcd1452eb7c20a3cb341eb1fdc9f64463c2fc61f64e38e6c2a2f1
after_success:
  - bundle exec codeclimate-test-reporter
deploy:
  provider: rubygems
  api_key:
    secure: 11xrMvbAapVtzF1t7yy/vzlZEWgxcVVOTWN29ERQEqPJxuSONBbge0NVzrSohDny8i+JFBehicJ1AkhuVz9VU/KF52xeTFxmz8AvFyTpSKwkZDjXEJAsCmRLchlihkv/XWPJ36KeXOJ6w6d6n+9SRcLxkdER3kbHLlf6bnGlg3ynqGxdTPh2bj8hAqkbXpDnSwJZl7bnqj/3WcPivPAOESN4Po8Ynp+H4Adb8nArtj0Kc4ed1+KvlejbmdsU5Nj6MYE3d54kviGiEimI6KQX7/jM3hX4HcaAtmXMPbyYPQN3E80zOnGSyPKphXQgQGAWdiTEsmBMGOvlRG6VsY0w27Y5cKnOTii43UQdve8VFtZjmZJwszbxu36UyHQ4aK3Ad1HKXFSqF3IQQx3ckLigcjQIEzrcYN679dCqDjEprl0Yaypfa8gzAHmf7BtaTY/CrMXh4oEy+hZkN0F6Ok/bKuulCkBguozci6uLUMhShXFOC7vK2k6WiA+MxTS4vYiKuKGTmVLf3uihAQ1FxYW9zEH8LxEmuF/C41kDyHx1ePcF9hAXFPl1qs/mgXBEO9DBcDYUV6H7ZhMt5BBITgcaoVgIx8O31gGIjKUY1eLfkIyw39/Qp+wiv8FTrfPJKo7YNYvGT2iTI3PeatQokNNE1g6wb1wnjcHpakiWBuPxW2o=
  gem: slack-logger
  on:
    tags: true
    repo: josephverbeck/slack-logger
